### ISSUE TITLE
feat: add models api

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#1708]
### Discussed in https://github.com/orgs/langfuse/discussions/1707

<div type='discussions-op-text'>

<sup>Originally posted by **rydamckinney** April 14, 2024</sup>
### Describe the feature or potential improvement

Requesting a POST (and GET to check current custom model definitions) API route for adding custom internal model pricing. Ideally an `externalId` can be provided to link the definition in langfuse to internal model db records

### Additional information

_No response_</div>

## Todo

- [ ] POST /models, user-defined ids, upsert on id
- [ ] GET /models
- [ ] GET /models/id
- [ ] Add to fern / openapi spec
- [ ] Add tests

**Comment by marcklingen** [comment]
Added in [https://github.com/langfuse/langfuse/pull/2531](https://github.com/langfuse/langfuse/pull/2531) and released in [https://github.com/langfuse/langfuse/releases/tag/v2.59.0](https://github.com/langfuse/langfuse/releases/tag/v2.59.0)
